### ISSUE TITLE
Extraer datos de las calificaciones del usuario

### ISSUE THREAD

**Issue by israv87** [EasyLab-ProyectoReto/EasyLab-Web#6]
- Realizar conexión heroku
- Obtener datos en formato Json

**Comment by cfjimbo** [comment]
## Rama asignada
https://api-easylab.herokuapp.com/ApiRest/Formulario?fbclid=IwAR0O6juItrqp2UJfWoD4tUEQueiyxmcvVLwLCr-FQfGgXFfFsgR8H4c8gXo ----- Link Json Heroku

[Estadistics](https://github.com/EasyLab-ProyectoReto/EasyLab-Web/tree/Estadistics) ---- Link commits extracción datos Json
