### ISSUE TITLE
API Web

### ISSUE THREAD

**Issue by israv87** [EasyLab-ProyectoReto/EasyLab-Web#9]
- Implementacion de API para la conexión entre la aplicaron de escritorio  y la plataforma  web
- Despliegue de Api a heroku

**Comment by JosePullaguariQ** [comment]
Trabajar en Repositorio EasyLab-API
Rama asignada: [endpoint-cruds-plataformaW](https://github.com/EasyLab-ProyectoReto/EasyLab-API/tree/endpoint-cruds-plataformaW)

**Comment by carlosalf9** [comment]
Commit sobre la Api Rest de Practicas para la conexion

96942f60f2e6acdf51621df56417fb626da865fd

**Comment by carlosalf9** [comment]
Trabajar en Repositorio EasyLab-API
Rama asignada:
endpoint-cruds-plataformaW
